"""add antibody profiles and sensitization events tables

Revision ID: 63c88b138992
Revises: db4b8f00ec39
Create Date: 2026-07-04 13:47:11.824173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c88b138992'
down_revision: Union[str, Sequence[str], None] = 'db4b8f00ec39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibody_profiles',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('antigen', sa.String(), nullable=False),
    sa.Column('mfi', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antibody_profiles_patient_id'), 'antibody_profiles', ['patient_id'], unique=False)
    op.create_table('sensitization_events',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('previous_transplant', 'pregnancy', 'blood_transfusion', name='sensitization_event_type_enum'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensitization_events_patient_id'), 'sensitization_events', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensitization_events_patient_id'), table_name='sensitization_events')
    op.drop_table('sensitization_events')
    op.drop_index(op.f('ix_antibody_profiles_patient_id'), table_name='antibody_profiles')
    op.drop_table('antibody_profiles')
    # ### end Alembic commands ###
