"""add nic_number to patients and donors

Revision ID: 8720582dd3e4
Revises: 61e9fdc21239
Create Date: 2026-07-08 02:16:21.221583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8720582dd3e4'
down_revision: Union[str, Sequence[str], None] = '61e9fdc21239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donors', sa.Column('nic_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_donors_nic_number'), 'donors', ['nic_number'], unique=True)
    op.add_column('patients', sa.Column('nic_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_patients_nic_number'), 'patients', ['nic_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_nic_number'), table_name='patients')
    op.drop_column('patients', 'nic_number')
    op.drop_index(op.f('ix_donors_nic_number'), table_name='donors')
    op.drop_column('donors', 'nic_number')
    # ### end Alembic commands ###
