"""add match reports table

Revision ID: b70a700c6e26
Revises: 63c88b138992
Create Date: 2026-07-04 13:56:23.366957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b70a700c6e26'
down_revision: Union[str, Sequence[str], None] = '63c88b138992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_reports',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('donor_id', sa.Uuid(), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('abo_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dsa_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitization_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hla_scoring_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cpra_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_reports_donor_id'), 'match_reports', ['donor_id'], unique=False)
    op.create_index(op.f('ix_match_reports_patient_id'), 'match_reports', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_reports_patient_id'), table_name='match_reports')
    op.drop_index(op.f('ix_match_reports_donor_id'), table_name='match_reports')
    op.drop_table('match_reports')
    # ### end Alembic commands ###
