"""add seq to audit_logs

Revision ID: d4f8b1a3c6e9
Revises: ae71d708307d
Create Date: 2026-08-09 17:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd4f8b1a3c6e9'
down_revision: Union[str, Sequence[str], None] = 'ae71d708307d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Review #2 bugs 1+2: create_audit_log/verify_audit_chain both ordered by
    created_at, tie-broken by an unindexed UUID -- a clock step backwards
    (NTP correction) between two writes could make the chain look
    permanently tampered, and there was no way to prove no row had been
    deleted from the middle of the chain (a gap in created_at values isn't
    distinguishable from "nothing happened in that window"). seq is a
    monotonically-increasing, gap-free-by-construction seed for both the
    write-order lookup and the verification walk -- immune to clock
    behavior, and any deleted middle row now leaves a detectable jump in
    the seq sequence (see verify_audit_chain's new check).

    No hash-formula change: prev_hash/hash already fully encode chain
    order between adjacent rows, so seq only needs to fix (a) the sort key
    and (b) gap detection, not be folded into the digest itself.

    Uses a native Postgres identity column (GENERATED BY DEFAULT AS
    IDENTITY) rather than a hand-managed sequence -- Postgres creates and
    owns the backing sequence itself, matching what
    app/models/audit_log.py's `Identity()` column produces via
    Base.metadata.create_all in the test suite, so both paths stay
    interchangeable.
    """
    # 1. Add as a plain nullable bigint first -- can't add NOT NULL/identity
    # directly onto a table that already has rows.
    op.add_column('audit_logs', sa.Column('seq', sa.BigInteger(), nullable=True))

    # 2. Backfill in the same order create_audit_log's tail lookup and
    # verify_audit_chain already used before this migration, so seq
    # reproduces true write order for every row that predates this column.
    op.execute(
        sa.text(
            "WITH ordered AS ("
            "  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC, id ASC) AS rn"
            "  FROM audit_logs"
            ") "
            "UPDATE audit_logs SET seq = ordered.rn "
            "FROM ordered WHERE audit_logs.id = ordered.id"
        )
    )

    # 3. Now safely enforce NOT NULL + uniqueness, then convert the column
    # into a real Postgres identity column seeded past the backfilled max
    # so the next INSERT (which omits seq entirely, letting Postgres
    # generate it) continues the sequence rather than restarting it.
    op.alter_column('audit_logs', 'seq', nullable=False)
    op.create_index(op.f('ix_audit_logs_seq'), 'audit_logs', ['seq'], unique=True)
    op.execute(
        "ALTER TABLE audit_logs ALTER COLUMN seq "
        "ADD GENERATED BY DEFAULT AS IDENTITY "
        "(START WITH 1)"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('audit_logs', 'seq'), "
        "COALESCE((SELECT MAX(seq) FROM audit_logs), 0) + 1, false)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE audit_logs ALTER COLUMN seq DROP IDENTITY IF EXISTS")
    op.drop_index(op.f('ix_audit_logs_seq'), table_name='audit_logs')
    op.drop_column('audit_logs', 'seq')
